-- 0045_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0045_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('room_packet.manage', 'Manage Room packet', 'Generate or edit a Room proposal: theme, agenda, venue options, guest ideas and economics. Internal record only.', 0, 0),
  ('room_packet.decide', 'Decide on a Room packet', 'Approve or decline a proposed Room. Human only in code — a Room commits the firm to spend and to approaching sponsors.', 0, 0),
  ('sponsor.manage', 'Manage sponsor prospect', 'Create or advance a sponsor prospect in the Room sponsorship pipeline. Internal record only; contacting the sponsor is an external effect.', 0, 0),
  ('community.act', 'Record a community act', 'Record something West Peek witnessed a member do — attended, hosted, answered, referred. Append-only evidence.', 0, 0),
  ('council.decide', 'Decide Council membership', 'Record a Council decision with a reason. Human only in code — the Council is a judgement, never a computed threshold.', 0, 0),
  ('match.manage', 'Manage introduction suggestions', 'Propose or dismiss a suggested introduction between two people. Proposing is internal; making the introduction is a human act.', 0, 0);
