-- 0051_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0051_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('opportunity.backfill', 'Backfill opportunity', 'Record a holding that predates the system by placing its status directly, permanently marked as backfilled with a reason. Separate from transition so authority over history is grantable on its own.', 0, 0);
