-- 0056_ai_employee_backfill.sql — generated by scripts/seed/generate-ai-employee-seed.mjs.
--
-- These employees' roles were changed after 0004 had already been applied to a live database.
-- The seeds there are INSERT OR IGNORE, so an existing row keeps its old value no matter how
-- many times 0004 is rewritten. This migration reaches the databases that already exist.
--
-- Each UPDATE is guarded on the row still holding a DIFFERENT value, so a database already
-- carrying the new one is untouched and re-applying changes nothing. Generated, not
-- hand-written: re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0056_ai_employee_backfill');

UPDATE ai_employee
   SET role = 'Scooter AI Chief of Staff', layer = 'MP Support'
 WHERE name = 'Walker'
   AND (role <> 'Scooter AI Chief of Staff' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Scooter AI Executive Assistant', layer = 'MP Support'
 WHERE name = 'Wendy'
   AND (role <> 'Scooter AI Executive Assistant' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Sequoia AI Chief of Staff', layer = 'MP Support'
 WHERE name = 'Wren'
   AND (role <> 'Sequoia AI Chief of Staff' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Sequoia AI Executive Assistant', layer = 'MP Support'
 WHERE name = 'Willa'
   AND (role <> 'Sequoia AI Executive Assistant' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Field Intake Coordinator', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Winton'
   AND (role <> 'Field Intake Coordinator' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Network OS Sync + Verification Mirror', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Porter'
   AND (role <> 'Network OS Sync + Verification Mirror' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Connection Intelligence / Warm Path Finder', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Winnie'
   AND (role <> 'Connection Intelligence / Warm Path Finder' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Community Manager', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Waverly'
   AND (role <> 'Community Manager' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Knowledge Manager', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Wells'
   AND (role <> 'Knowledge Manager' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Compliance + Privacy Gatekeeper / Compliance Linter', layer = 'Intake/Relationship/Memory/Governance + LP'
 WHERE name = 'Willow'
   AND (role <> 'Compliance + Privacy Gatekeeper / Compliance Linter' OR layer <> 'Intake/Relationship/Memory/Governance + LP');

UPDATE ai_employee
   SET role = 'Systems Operator', layer = 'Intake/Relationship/Memory/Governance'
 WHERE name = 'Wilson'
   AND (role <> 'Systems Operator' OR layer <> 'Intake/Relationship/Memory/Governance');

UPDATE ai_employee
   SET role = 'Principal', layer = 'Investment/IC/Meeting'
 WHERE name = 'Pierce'
   AND (role <> 'Principal' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'Associate', layer = 'Investment/IC/Meeting'
 WHERE name = 'Priya'
   AND (role <> 'Associate' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'Research Analyst', layer = 'Investment/IC/Meeting'
 WHERE name = 'Paige'
   AND (role <> 'Research Analyst' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'Deal Watchlist Analyst', layer = 'Investment/IC/Meeting'
 WHERE name = 'Wyatt'
   AND (role <> 'Deal Watchlist Analyst' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'IC Facilitator', layer = 'Investment/IC/Meeting'
 WHERE name = 'Poppy'
   AND (role <> 'IC Facilitator' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'Meeting Buddy', layer = 'Investment/IC/Meeting'
 WHERE name = 'Walter'
   AND (role <> 'Meeting Buddy' OR layer <> 'Investment/IC/Meeting');

UPDATE ai_employee
   SET role = 'LP Sourcer', layer = 'LP/Fundraising'
 WHERE name = 'Piper'
   AND (role <> 'LP Sourcer' OR layer <> 'LP/Fundraising');

UPDATE ai_employee
   SET role = 'Enrichment + Scoring Agent', layer = 'LP/Fundraising'
 WHERE name = 'Perry'
   AND (role <> 'Enrichment + Scoring Agent' OR layer <> 'LP/Fundraising');

UPDATE ai_employee
   SET role = 'LP Relations Manager', layer = 'LP/Fundraising'
 WHERE name = 'Wesley'
   AND (role <> 'LP Relations Manager' OR layer <> 'LP/Fundraising');

UPDATE ai_employee
   SET role = 'Outreach Composer', layer = 'LP/Fundraising'
 WHERE name = 'Penn'
   AND (role <> 'Outreach Composer' OR layer <> 'LP/Fundraising');

UPDATE ai_employee
   SET role = 'Portfolio Support Manager', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Winter'
   AND (role <> 'Portfolio Support Manager' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Event Marketing Coordinator', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Parker'
   AND (role <> 'Event Marketing Coordinator' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Sponsorship Scout', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Wynn'
   AND (role <> 'Sponsorship Scout' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Marketing Lead', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Percy'
   AND (role <> 'Marketing Lead' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'PR Lead', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Prue'
   AND (role <> 'PR Lead' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Content Manager', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Pippa'
   AND (role <> 'Content Manager' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Operations Manager', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Pax'
   AND (role <> 'Operations Manager' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Finance Support', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Preston'
   AND (role <> 'Finance Support' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Fund Admin Coordinator', layer = 'Portfolio/Event/Brand/Ops'
 WHERE name = 'Perrin'
   AND (role <> 'Fund Admin Coordinator' OR layer <> 'Portfolio/Event/Brand/Ops');

UPDATE ai_employee
   SET role = 'Market Intelligence Coach', layer = 'Market Intelligence (deferred product)'
 WHERE name = 'Whitney'
   AND (role <> 'Market Intelligence Coach' OR layer <> 'Market Intelligence (deferred product)');
