-- 0057_ai_employee_backfill.sql — generated by scripts/seed/generate-ai-employee-seed.mjs.
--
-- These employees' roles were changed after 0004 had already been applied to a live database.
-- The seeds there are INSERT OR IGNORE, so an existing row keeps its old value no matter how
-- many times 0004 is rewritten. This migration reaches the databases that already exist.
--
-- Each UPDATE is guarded on the row still holding a DIFFERENT value, so a database already
-- carrying the new one is untouched and re-applying changes nothing. Generated, not
-- hand-written: re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0057_ai_employee_backfill');

UPDATE ai_employee
   SET role = 'Scooter''s Chief of Staff', layer = 'MP Support'
 WHERE name = 'Walker'
   AND (role <> 'Scooter''s Chief of Staff' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Sequoia''s Chief of Staff', layer = 'MP Support'
 WHERE name = 'Wren'
   AND (role <> 'Sequoia''s Chief of Staff' OR layer <> 'MP Support');

UPDATE ai_employee
   SET role = 'Systems & Intake Operator', layer = 'Firm operations'
 WHERE name = 'Porter'
   AND (role <> 'Systems & Intake Operator' OR layer <> 'Firm operations');

UPDATE ai_employee
   SET role = 'Relationships & Community', layer = 'Firm operations'
 WHERE name = 'Waverly'
   AND (role <> 'Relationships & Community' OR layer <> 'Firm operations');

UPDATE ai_employee
   SET role = 'Compliance & Privacy', layer = 'Firm operations'
 WHERE name = 'Willow'
   AND (role <> 'Compliance & Privacy' OR layer <> 'Firm operations');

UPDATE ai_employee
   SET role = 'Investment Lead', layer = 'Investment'
 WHERE name = 'Pierce'
   AND (role <> 'Investment Lead' OR layer <> 'Investment');

UPDATE ai_employee
   SET role = 'Analyst & Scout', layer = 'Investment'
 WHERE name = 'Wyatt'
   AND (role <> 'Analyst & Scout' OR layer <> 'Investment');

UPDATE ai_employee
   SET role = 'LP Sourcing', layer = 'LP & fundraising'
 WHERE name = 'Piper'
   AND (role <> 'LP Sourcing' OR layer <> 'LP & fundraising');

UPDATE ai_employee
   SET role = 'LP Relations', layer = 'LP & fundraising'
 WHERE name = 'Wesley'
   AND (role <> 'LP Relations' OR layer <> 'LP & fundraising');

UPDATE ai_employee
   SET role = 'Portfolio Support', layer = 'Portfolio & operations'
 WHERE name = 'Winter'
   AND (role <> 'Portfolio Support' OR layer <> 'Portfolio & operations');

UPDATE ai_employee
   SET role = 'Communications', layer = 'Portfolio & operations'
 WHERE name = 'Pippa'
   AND (role <> 'Communications' OR layer <> 'Portfolio & operations');

UPDATE ai_employee
   SET role = 'Finance & Fund Admin', layer = 'Portfolio & operations'
 WHERE name = 'Preston'
   AND (role <> 'Finance & Fund Admin' OR layer <> 'Portfolio & operations');
