-- 0071_ai_employee_retire.sql — generated by scripts/seed/generate-ai-employee-seed.mjs.
--
-- Employees consolidated off the roster. Their rows stay: ai_run attribution, meeting seating
-- and work cards reference them, and what they did actually happened. RETIRED is the lifecycle's
-- existing word for a seat that no longer exists, so nothing new is introduced here.
--
-- Guarded so re-applying changes nothing, and so an already-RETIRED row is left alone.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0071_ai_employee_retire');

UPDATE ai_employee
   SET status = 'RETIRED'
 WHERE name NOT IN ('Walker', 'Wren', 'Porter', 'Waverly', 'Wells', 'Willow', 'Pierce', 'Wyatt', 'Poppy', 'Walter', 'Piper', 'Wesley', 'Winter', 'Parker', 'Pippa', 'Pax', 'Preston', 'Whitney')
   AND status <> 'RETIRED';
