-- 0074_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0074_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('deliverable.deliver', 'Hand over a deliverable', 'Record something an employee produced — a brief, a review, a research packet — and file a copy in Documents.', 0, 0),
  ('deliverable.email_self', 'Email a deliverable to a partner', 'Send a deliverable to a Managing Partner''s own registered address. Cannot reach any address outside the firm.', 0, 0);
