-- 0076_ai_employee_backfill.sql — generated by scripts/seed/generate-ai-employee-seed.mjs.
--
-- These employees' roles were changed after 0004 had already been applied to a live database.
-- The seeds there are INSERT OR IGNORE, so an existing row keeps its old value no matter how
-- many times 0004 is rewritten. This migration reaches the databases that already exist.
--
-- Each UPDATE is guarded on the row still holding a DIFFERENT value, so a database already
-- carrying the new one is untouched and re-applying changes nothing. Generated, not
-- hand-written: re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0076_ai_employee_backfill');

UPDATE ai_employee
   SET role = 'Design & Conversion Review', layer = 'Portfolio & operations'
 WHERE name = 'Percy'
   AND (role <> 'Design & Conversion Review' OR layer <> 'Portfolio & operations');

-- Un-retire him. The generated block above fixes his ROLE; this fixes his lifecycle.
--
-- INACTIVE, not ACTIVE. Activation needs a Managing Partner receipt (D10) and a migration cannot
-- carry one — the same lesson 0069 learned and 0070 corrected. He goes back on the roster where
-- every other seat starts, and activating him is one click on Team -> Employees.
UPDATE ai_employee
SET status = 'INACTIVE', layer = 'Portfolio & operations'
WHERE name = 'Percy' AND status = 'RETIRED';

UPDATE ai_employee_profile
SET department = 'Portfolio & operations',
    brief = 'Design & Conversion Review. Judges a page from screenshots at two widths and refuses to review one he could not see.',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE ai_employee_id = (SELECT id FROM ai_employee WHERE name = 'Percy');

INSERT INTO ai_employee_status_history (id, ai_employee_id, from_status, to_status, actor_type, actor_id, reason)
SELECT 'aesh_percy_design_0076', id, 'RETIRED', 'INACTIVE', 'SYSTEM', 'migration:0076',
       'Un-retired as Design & Conversion Review. Marketing, PR and content merged into Pippa in '
       || 'roster v4.0; the half that did not survive — whether somebody else''s page actually '
       || 'works — is what the firm could not answer, so the seat was re-pointed rather than a '
       || 'nineteenth invented.'
FROM ai_employee WHERE name = 'Percy';
