-- 0078_ai_employee_backfill.sql — generated by scripts/seed/generate-ai-employee-seed.mjs.
--
-- These employees' roles were changed after 0004 had already been applied to a live database.
-- The seeds there are INSERT OR IGNORE, so an existing row keeps its old value no matter how
-- many times 0004 is rewritten. This migration reaches the databases that already exist.
--
-- Each UPDATE is guarded on the row still holding a DIFFERENT value, so a database already
-- carrying the new one is untouched and re-applying changes nothing. Generated, not
-- hand-written: re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0078_ai_employee_backfill');

UPDATE ai_employee
   SET role = 'UX Design & Growth', layer = 'Portfolio & operations'
 WHERE name = 'Percy'
   AND (role <> 'UX Design & Growth' OR layer <> 'Portfolio & operations');
