-- 0100_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0100_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('network_os.propose_person', 'Propose a person to Network OS', 'Send a captured person to Network OS''s intake queue for a human there to review. Never writes a contact.', 1, 0);
