-- 0102_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0102_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('lp_commitment.record', 'Record an LP commitment', 'Record or revise how much a limited partner has committed to a fund.', 0, 0),
  ('fund.set_size', 'Set the fund''s target size', 'State what the fund is raising. What has actually been committed is derived from signed commitments, never typed.', 0, 0);
