-- 0108_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0108_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('position.mark', 'Mark a holding', 'Record what a position is worth now, on what basis, as of when. Append-only; a mark is superseded, never edited.', 0, 0),
  ('capital_call.record', 'Record a capital call', 'Record capital called from a limited partner against their commitment.', 0, 0),
  ('capital_distribution.record', 'Record a distribution', 'Record cash paid back to a limited partner.', 0, 0);
