-- 0128_action_types_backfill.sql — generated by scripts/seed/generate-machine-seed.mjs.
--
-- These action keys were added to the registry after 0003 had already been applied to a live
-- database. Rewriting 0003 reaches new databases only; this migration reaches the existing
-- ones. Without it authorize() denies the key and the feature 403s in production while
-- passing every local test.
--
-- Generated, not hand-written. Re-run the seed generator rather than editing this.

INSERT OR IGNORE INTO schema_version (migration) VALUES ('0128_action_types_backfill');

INSERT OR IGNORE INTO action_type (key, name, description, is_external_effect, is_reserved) VALUES
  ('approval.reopen', 'Change a decision already made', 'Record a new decision that supersedes an earlier one on the same card, with a required reason. The original decision is never edited or erased, and something already carried out can never be reopened.', 0, 0),
  ('approval.block', 'Block an approval', 'Stop an approval proceeding until a named blocker is resolved. Unlike a rejection this is not a verdict on the request: it names what the firm is waiting for, and it can be released.', 0, 0),
  ('approval.block_release', 'Release a block', 'Record that what an approval was waiting on is resolved, returning the card to exactly the state it was in when the block landed.', 0, 0);
